### ISSUE TITLE
Falta de permissão em instalação de pacotes

### ISSUE THREAD

**Issue by lucastamoios** [mbodock/ansible-asuka#4]
As instalações do [tmux](https://github.com/mbodock/ansible-asuka/blob/master/roles/tmux/tasks/main.yml) e do [cpufrequtils](https://github.com/mbodock/ansible-asuka/blob/master/roles/scripts/tasks/main.yml) devem ter o atributo `become: yes`.

**Comment by mbodock** [comment]
Aceito PR!
